package com.mrf.tghost.app.ui.theme

import androidx.compose.ui.graphics.Color


val primaryLight = Color(0xFF5A631F)
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFDEEA96)
val onPrimaryContainerLight = Color(0xFF424B06)
val secondaryLight = Color(0xFF5D6145)
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE2E5C2)
val onSecondaryContainerLight = Color(0xFF45492F)
val tertiaryLight = Color(0xFF3B665B)
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFBDECDE)
val onTertiaryContainerLight = Color(0xFF224E44)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF93000A)
val backgroundLight = Color(0xFFFCFAED)
val onBackgroundLight = Color(0xFF1B1C15)
val surfaceLight = Color(0xFFFCFAED)
val onSurfaceLight = Color(0xFF1B1C15)
val surfaceVariantLight = Color(0xFFE4E3D2)
val onSurfaceVariantLight = Color(0xFF47483B)
val outlineLight = Color(0xFF77786A)
val outlineVariantLight = Color(0xFFC8C7B7)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF303129)
val inverseOnSurfaceLight = Color(0xFFF3F1E4)
val inversePrimaryLight = Color(0xFFC2CD7C)
val surfaceDimLight = Color(0xFFDCDACE)
val surfaceBrightLight = Color(0xFFFCFAED)
val surfaceContainerLowestLight = Color(0xFFFFFFFF)
val surfaceContainerLowLight = Color(0xFFF6F4E7)
val surfaceContainerLight = Color(0xFFF0EEE1)
val surfaceContainerHighLight = Color(0xFFEAE9DC)
val surfaceContainerHighestLight = Color(0xFFE4E3D6)

val primaryLightMediumContrast = Color(0xFF323A00)
val onPrimaryLightMediumContrast = Color(0xFFFFFFFF)
val primaryContainerLightMediumContrast = Color(0xFF69722C)
val onPrimaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val secondaryLightMediumContrast = Color(0xFF353820)
val onSecondaryLightMediumContrast = Color(0xFFFFFFFF)
val secondaryContainerLightMediumContrast = Color(0xFF6C6F52)
val onSecondaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryLightMediumContrast = Color(0xFF0E3D33)
val onTertiaryLightMediumContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightMediumContrast = Color(0xFF4A756A)
val onTertiaryContainerLightMediumContrast = Color(0xFFFFFFFF)
val errorLightMediumContrast = Color(0xFF740006)
val onErrorLightMediumContrast = Color(0xFFFFFFFF)
val errorContainerLightMediumContrast = Color(0xFFCF2C27)
val onErrorContainerLightMediumContrast = Color(0xFFFFFFFF)
val backgroundLightMediumContrast = Color(0xFFFCFAED)
val onBackgroundLightMediumContrast = Color(0xFF1B1C15)
val surfaceLightMediumContrast = Color(0xFFFCFAED)
val onSurfaceLightMediumContrast = Color(0xFF11120B)
val surfaceVariantLightMediumContrast = Color(0xFFE4E3D2)
val onSurfaceVariantLightMediumContrast = Color(0xFF36372B)
val outlineLightMediumContrast = Color(0xFF525346)
val outlineVariantLightMediumContrast = Color(0xFF6D6E60)
val scrimLightMediumContrast = Color(0xFF000000)
val inverseSurfaceLightMediumContrast = Color(0xFF303129)
val inverseOnSurfaceLightMediumContrast = Color(0xFFF3F1E4)
val inversePrimaryLightMediumContrast = Color(0xFFC2CD7C)
val surfaceDimLightMediumContrast = Color(0xFFC8C7BB)
val surfaceBrightLightMediumContrast = Color(0xFFFCFAED)
val surfaceContainerLowestLightMediumContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightMediumContrast = Color(0xFFF6F4E7)
val surfaceContainerLightMediumContrast = Color(0xFFEAE9DC)
val surfaceContainerHighLightMediumContrast = Color(0xFFDFDDD1)
val surfaceContainerHighestLightMediumContrast = Color(0xFFD3D2C6)

val primaryLightHighContrast = Color(0xFF292F00)
val onPrimaryLightHighContrast = Color(0xFFFFFFFF)
val primaryContainerLightHighContrast = Color(0xFF454E09)
val onPrimaryContainerLightHighContrast = Color(0xFFFFFFFF)
val secondaryLightHighContrast = Color(0xFF2B2E16)
val onSecondaryLightHighContrast = Color(0xFFFFFFFF)
val secondaryContainerLightHighContrast = Color(0xFF484B31)
val onSecondaryContainerLightHighContrast = Color(0xFFFFFFFF)
val tertiaryLightHighContrast = Color(0xFF00332A)
val onTertiaryLightHighContrast = Color(0xFFFFFFFF)
val tertiaryContainerLightHighContrast = Color(0xFF255146)
val onTertiaryContainerLightHighContrast = Color(0xFFFFFFFF)
val errorLightHighContrast = Color(0xFF600004)
val onErrorLightHighContrast = Color(0xFFFFFFFF)
val errorContainerLightHighContrast = Color(0xFF98000A)
val onErrorContainerLightHighContrast = Color(0xFFFFFFFF)
val backgroundLightHighContrast = Color(0xFFFCFAED)
val onBackgroundLightHighContrast = Color(0xFF1B1C15)
val surfaceLightHighContrast = Color(0xFFFCFAED)
val onSurfaceLightHighContrast = Color(0xFF000000)
val surfaceVariantLightHighContrast = Color(0xFFE4E3D2)
val onSurfaceVariantLightHighContrast = Color(0xFF000000)
val outlineLightHighContrast = Color(0xFF2C2D22)
val outlineVariantLightHighContrast = Color(0xFF494A3E)
val scrimLightHighContrast = Color(0xFF000000)
val inverseSurfaceLightHighContrast = Color(0xFF303129)
val inverseOnSurfaceLightHighContrast = Color(0xFFFFFFFF)
val inversePrimaryLightHighContrast = Color(0xFFC2CD7C)
val surfaceDimLightHighContrast = Color(0xFFBAB9AD)
val surfaceBrightLightHighContrast = Color(0xFFFCFAED)
val surfaceContainerLowestLightHighContrast = Color(0xFFFFFFFF)
val surfaceContainerLowLightHighContrast = Color(0xFFF3F1E4)
val surfaceContainerLightHighContrast = Color(0xFFE4E3D6)
val surfaceContainerHighLightHighContrast = Color(0xFFD6D5C8)
val surfaceContainerHighestLightHighContrast = Color(0xFFC8C7BB)

val primaryDark = Color(0xFFC2CD7C)
val onPrimaryDark = Color(0xFF2D3400)
val primaryContainerDark = Color(0xFF424B06)
val onPrimaryContainerDark = Color(0xFFDEEA96)
val secondaryDark = Color(0xFFC6C9A7)
val onSecondaryDark = Color(0xFF2F321A)
val secondaryContainerDark = Color(0xFF45492F)
val onSecondaryContainerDark = Color(0xFFE2E5C2)
val tertiaryDark = Color(0xFFA2D0C2)
val onTertiaryDark = Color(0xFF06372E)
val tertiaryContainerDark = Color(0xFF224E44)
val onTertiaryContainerDark = Color(0xFFBDECDE)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF13140D)
val onBackgroundDark = Color(0xFFE4E3D6)
val surfaceDark = Color(0xFF13140D)
val onSurfaceDark = Color(0xFFE4E3D6)
val surfaceVariantDark = Color(0xFF47483B)
val onSurfaceVariantDark = Color(0xFFC8C7B7)
val outlineDark = Color(0xFF919283)
val outlineVariantDark = Color(0xFF47483B)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFE4E3D6)
val inverseOnSurfaceDark = Color(0xFF303129)
val inversePrimaryDark = Color(0xFF5A631F)
val surfaceDimDark = Color(0xFF13140D)
val surfaceBrightDark = Color(0xFF393A31)
val surfaceContainerLowestDark = Color(0xFF0E0F08)
val surfaceContainerLowDark = Color(0xFF1B1C15)
val surfaceContainerDark = Color(0xFF1F2018)
val surfaceContainerHighDark = Color(0xFF2A2B22)
val surfaceContainerHighestDark = Color(0xFF35352D)

val primaryDarkMediumContrast = Color(0xFFD8E390)
val onPrimaryDarkMediumContrast = Color(0xFF232800)
val primaryContainerDarkMediumContrast = Color(0xFF8C974C)
val onPrimaryContainerDarkMediumContrast = Color(0xFF000000)
val secondaryDarkMediumContrast = Color(0xFFDCDFBC)
val onSecondaryDarkMediumContrast = Color(0xFF242710)
val secondaryContainerDarkMediumContrast = Color(0xFF909374)
val onSecondaryContainerDarkMediumContrast = Color(0xFF000000)
val tertiaryDarkMediumContrast = Color(0xFFB7E6D8)
val onTertiaryDarkMediumContrast = Color(0xFF002C23)
val tertiaryContainerDarkMediumContrast = Color(0xFF6D9A8D)
val onTertiaryContainerDarkMediumContrast = Color(0xFF000000)
val errorDarkMediumContrast = Color(0xFFFFD2CC)
val onErrorDarkMediumContrast = Color(0xFF540003)
val errorContainerDarkMediumContrast = Color(0xFFFF5449)
val onErrorContainerDarkMediumContrast = Color(0xFF000000)
val backgroundDarkMediumContrast = Color(0xFF13140D)
val onBackgroundDarkMediumContrast = Color(0xFFE4E3D6)
val surfaceDarkMediumContrast = Color(0xFF13140D)
val onSurfaceDarkMediumContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkMediumContrast = Color(0xFF47483B)
val onSurfaceVariantDarkMediumContrast = Color(0xFFDEDDCC)
val outlineDarkMediumContrast = Color(0xFFB3B3A3)
val outlineVariantDarkMediumContrast = Color(0xFF919182)
val scrimDarkMediumContrast = Color(0xFF000000)
val inverseSurfaceDarkMediumContrast = Color(0xFFE4E3D6)
val inverseOnSurfaceDarkMediumContrast = Color(0xFF2A2B22)
val inversePrimaryDarkMediumContrast = Color(0xFF444C07)
val surfaceDimDarkMediumContrast = Color(0xFF13140D)
val surfaceBrightDarkMediumContrast = Color(0xFF45453C)
val surfaceContainerLowestDarkMediumContrast = Color(0xFF070803)
val surfaceContainerLowDarkMediumContrast = Color(0xFF1D1E16)
val surfaceContainerDarkMediumContrast = Color(0xFF282820)
val surfaceContainerHighDarkMediumContrast = Color(0xFF33332B)
val surfaceContainerHighestDarkMediumContrast = Color(0xFF3E3E35)

val primaryDarkHighContrast = Color(0xFFECF7A2)
val onPrimaryDarkHighContrast = Color(0xFF000000)
val primaryContainerDarkHighContrast = Color(0xFFBEC979)
val onPrimaryContainerDarkHighContrast = Color(0xFF0A0D00)
val secondaryDarkHighContrast = Color(0xFFF0F3CF)
val onSecondaryDarkHighContrast = Color(0xFF000000)
val secondaryContainerDarkHighContrast = Color(0xFFC2C5A3)
val onSecondaryContainerDarkHighContrast = Color(0xFF0A0D00)
val tertiaryDarkHighContrast = Color(0xFFCBFAEB)
val onTertiaryDarkHighContrast = Color(0xFF000000)
val tertiaryContainerDarkHighContrast = Color(0xFF9ECCBE)
val onTertiaryContainerDarkHighContrast = Color(0xFF000E0A)
val errorDarkHighContrast = Color(0xFFFFECE9)
val onErrorDarkHighContrast = Color(0xFF000000)
val errorContainerDarkHighContrast = Color(0xFFFFAEA4)
val onErrorContainerDarkHighContrast = Color(0xFF220001)
val backgroundDarkHighContrast = Color(0xFF13140D)
val onBackgroundDarkHighContrast = Color(0xFFE4E3D6)
val surfaceDarkHighContrast = Color(0xFF13140D)
val onSurfaceDarkHighContrast = Color(0xFFFFFFFF)
val surfaceVariantDarkHighContrast = Color(0xFF47483B)
val onSurfaceVariantDarkHighContrast = Color(0xFFFFFFFF)
val outlineDarkHighContrast = Color(0xFFF2F1E0)
val outlineVariantDarkHighContrast = Color(0xFFC4C3B3)
val scrimDarkHighContrast = Color(0xFF000000)
val inverseSurfaceDarkHighContrast = Color(0xFFE4E3D6)
val inverseOnSurfaceDarkHighContrast = Color(0xFF000000)
val inversePrimaryDarkHighContrast = Color(0xFF444C07)
val surfaceDimDarkHighContrast = Color(0xFF13140D)
val surfaceBrightDarkHighContrast = Color(0xFF505147)
val surfaceContainerLowestDarkHighContrast = Color(0xFF000000)
val surfaceContainerLowDarkHighContrast = Color(0xFF1F2018)
val surfaceContainerDarkHighContrast = Color(0xFF303129)
val surfaceContainerHighDarkHighContrast = Color(0xFF3B3C33)
val surfaceContainerHighestDarkHighContrast = Color(0xFF47473E)








val errorRed = Color(0xFFFF0000)

val primaryWhite = Color(0xFFF5F5F5)
val primaryBlack = Color(0xFF070706)
val primaryRed = Color(0xFFD20000)
val primaryGreen = Color(0xFF228F6E)
val secondaryGreen = Color(0xFF010F10)
val containerGreen = Color(0xFFDEEF76)

//val tertiaryLight = primaryWhite
//val tertiaryDark = primaryWhite
val tertiaryRed = primaryWhite
val tertiaryBlue = primaryWhite
val tertiaryPurple = primaryWhite
val tertiaryGreen = primaryWhite

val redThemePrimary = Color(0xFF8A3C46)
val redThemeOnPrimary = Color(0xFFF5F5F5)

val blueThemePrimary = Color(0xFF4576B7)
val blueThemeOnPrimary = Color(0xFFF5F5F5)

val purpleThemePrimary = Color(0xFF8E52B0)
val purpleThemeOnPrimary = Color(0xFFF5F5F5)

val orangeThemePrimary = Color(0xFFEEA158)
val orangeThemeOnPrimary = primaryBlack



